### ISSUE TITLE
Group of requests disappear when dropped inside own group

### ISSUE THREAD

**Issue by aliasbody** [mmattozzi/cocoa-rest-client#100]
There is a bug on the drawer section and it is quite simple to replicate:

1. Create a "groupe" on the drawer
2. Save a request and drop it inside that group
3. Drag and Drop the group inside of itself
4. The group (and all the sub-requests) are gone

And don't know why this happens, but it has happened to me quite a lot to not notice it.

Appart from that, great job! It is a great tool that I'm using everyday for my work :)

**Comment by mmattozzi** [comment]
I think this should be easy to fix; the code doesn't check if the object being dropped is equivalent to the target it is dropped on. 

Thanks for the bug report and the kind comments... also congrats on being issue #100. 💯

**Comment by mmattozzi** [comment]
Fixed in Release [1.3.13](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.13)

**Comment by aliasbody** [comment]
Thank you :) !
