### ISSUE TITLE
post image error

### ISSUE THREAD

**Issue by hzb** [mmattozzi/cocoa-rest-client#101]
Please look at following image

![2016-05-26 09 54 40](https://cloud.githubusercontent.com/assets/535675/15561407/111eae3a-2328-11e6-8427-140be0b893fc.png)

I try to post a image to my server, and it shows this error, but my server works fine, am I use cocoarestclient wrong?

**Comment by mmattozzi** [comment]
The file upload tab currently only supports HTTP multipart upload. Is that the kind of upload you are doing or are you trying to post the bytes of the image to the URL (kind of like an Amazon S3 upload)?

**Comment by bhua** [comment]
@mmattozzi The url is 'http://domain.com/upload.php', the file 'upload.php' code like this

```php
$file = $_FILE["touxiang"]["name"];
```

**Comment by mmattozzi** [comment]
Do you have a sample curl command that does work? If you're using the latest version of CocoaRestClient and generate a curl command (Command-K), paste it in the command line... does that work?
