### ISSUE TITLE
Pressing Cmd-Backspace in Text Input fields deletes saved requests

### ISSUE THREAD

**Issue by georgberky** [mmattozzi/cocoa-rest-client#106]
Hi,

I'm using Cocoa Version 1.3.13 (18) installed from homebrew caskroom on OSX. When I want to save a request, a text field pops up where I can enter the name for saving the request.

If I press Cmd-Backspace (which is usually the combination to clear out a whole line of text in a text field or text area), Cocoa deletes a request from the saved request list instead.

The same happens when editing header names or values.

I just lost three saved requests because of that. Please disable the combination or make it behave as expected.

Thank you in advance,

Georg

**Comment by mmattozzi** [comment]
Fixed in Release 1.3.15, forgot to close issue earlier.
