### ISSUE TITLE
Make changing request method quicker

### ISSUE THREAD

**Issue by gdubicki** [mmattozzi/cocoa-rest-client#108]
When I do a few requests with different methods one after another I find the UI for switching the method annoying.

Particularly to change from DELETE to GET I have to do these three steps:
1. Click on the _small_ drop-down button
2. Scroll the list up (as the top element I see is DELETE and GET is above it)
3. Click GET
= 2 clicks, including 1 on a small element, and scrolling!

The following changes to the UI would make the first click easier and save the scrolling:
1. Make drop-down text field non-editable to enable clicking on it as a whole instead of only the small drop-down button (does anyone need to enter the method manually?)
2. Always show all 9 positions on the drop-down list

Additionally adding keyboard shortcuts to change the method would also be nice.

**Comment by mmattozzi** [comment]
Over the years, I've found that people use all kinds of non-standard, exotic HTTP verbs that they want the app to support... that's why I ended up making the method editable. 

I'll investigate showing the entire list on dropdown or maybe mapping some keys.

**Comment by gdubicki** [comment]
Thanks for a quick reply!

Maybe add a setting for that then: method editable yes/no? But then please make it disabled by default or implement it along with #109. :)

**Comment by gdubicki** [comment]
Hey, how's checking out making all 9 positions visible going? That seems to be a really quick fix for my issue.

**Comment by mmattozzi** [comment]
All methods are now visible in the dropdown in [1.4.1](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.1)
