### ISSUE TITLE
Pretty print custom variants of JSON

### ISSUE THREAD

**Issue by jlecour** [mmattozzi/cocoa-rest-client#11]
Hi,

I'm using a custom variant of the JSON Mime type : `application/vnc.example-v1+json`
It is not formatted as regular JSON content.

Is there a way to customize the mapping between formatters and Mime type?
It doesn't have to be a nice GUI, a setting in a plist file would be great.

Thanks for your work on this piece of software.

**Comment by Relequestual** [comment]
Based on my readings of the HTTP spec regarding content type, a standard format seems to be application/[some_stuff]+json. Could anything that follows that pattern be considered json and therefore formatted as json?

**Comment by mmattozzi** [comment]
That seems like a reasonable approach.

**Comment by Relequestual** [comment]
It looks like this has been fixed in the latest version (1.3.9 (14)) or possibly before. Think this can be closed now! =D Thanks!

**Comment by Relequestual** [comment]
No longer fixed in Version 1.3.11 (16) =[

**Comment by mmattozzi** [comment]
Fixed again in [1.3.14](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.14)!
