### ISSUE TITLE
Make Menu Items Consistent with Standards

### ISSUE THREAD

**Issue by johnyradio** [mmattozzi/cocoa-rest-client#113]
hi

thx for great app!

Plz change:
"Overwrite request" to "Save"
and 
"Save Request" to "Save As"

thx!

**Comment by mmattozzi** [comment]
Fixed in [Release 1.3.16](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.16).

**Comment by johnyradio** [comment]
thx!
