### ISSUE TITLE
How send JSON in POST body?

### ISSUE THREAD

**Issue by edalzell** [mmattozzi/cocoa-rest-client#118]
I can't figure out how to send JSON in the request body for a POST request.

![cocoarestclient 2016-09-28 20-43-48](https://cloud.githubusercontent.com/assets/6069653/18940357/4a4e4cb4-85bc-11e6-8fae-b96713fbfe80.png)
![cocoarestclient 2016-09-28 20-43-35](https://cloud.githubusercontent.com/assets/6069653/18940358/4a6cf90c-85bc-11e6-81c0-36923fb3baea.png)

What am I doing wrong?

**Comment by mmattozzi** [comment]
Looks like you're missing a comma in your json for one thing...

**Comment by edalzell** [comment]
Wow, that did it. PEBKAC.
