### ISSUE TITLE
Saved requests still has focus while typing name of new query after cmd+s

### ISSUE THREAD

**Issue by adroitandroid** [mmattozzi/cocoa-rest-client#120]
What implication this has is... for the new query I would like to give a new name and cmd+delete removes text from most places I'm familiar with BUT here my saved request which was last selected gets deleted :( please fix this, it is very annoying.
Thanks for the rest of the wonderful work btw!

**Comment by mmattozzi** [comment]
Oh, look at that. Let me see what I can do.

**Comment by adroitandroid** [comment]
Fixed, thanks!
