### ISSUE TITLE
Get request not sending Authorization Token

### ISSUE THREAD

**Issue by alex-gee** [mmattozzi/cocoa-rest-client#121]
It seems that if I want to send a authorization token on a GET request it is simply not send in the header.
If I change to POST it is sended. Is this intended?

**Comment by mmattozzi** [comment]
If you're talking about the `Authorization` header, this seems to work both in the Headers tab and the Auth tab for the request. 

![screen shot 2017-04-14 at 5 22 31 pm](https://cloud.githubusercontent.com/assets/74625/25056488/28b9abae-2137-11e7-8b29-d3e8470c5c11.png)

![screen shot 2017-04-14 at 5 22 54 pm](https://cloud.githubusercontent.com/assets/74625/25056491/30f29eca-2137-11e7-9a8d-a5a8fcd5b4b3.png)

**Comment by serjant** [comment]
It does not send Authorization header when sending the DELETE request
