### ISSUE TITLE
Pod problems for Sparkle?

### ISSUE THREAD

**Issue by jrusoff** [mmattozzi/cocoa-rest-client#122]
I've just downloaded the latest zip and tried to build. When I run pod install, it can't find the Sparkle pod:  /usr/bin/curl -f -L -o /var/folders/f1/3l6d68t962bb_gycjwggsr_1r4fcsm/T/d20170126-3027-5k9dbb/file.tbz https://github.com/sparkle-project/Sparkle/releases/download/1.8.0/Sparkle-1.8.0.tar.bz2 --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (22) The requested URL returned error: 404 Not Found

Any idea where I've gone wrong? I set up a public SSH key in gitHub. 1.8 looks like an old version of Sparkle. Could it be outdated?
Thanks,
Jason
jrusoff@me.com

**Comment by mmattozzi** [comment]
Interesting... did you ever overcome this? If I check out the project to `/tmp` on my computer and run `pod install` it looks like it picks up Sparkle version 1.14.0. I don't actually specify a version of Sparkle in Podfile, so it should just pick up the latest version available for whatever OS (or maybe xcode??) version you're running.

**Comment by jrusoff** [comment]
It was something wrong within our firewall. I ended up downloading the latest Sparkle version and installing it manually. Everything is working now.
Thanks
Jason
