### ISSUE TITLE
Multiwindow

### ISSUE THREAD

**Issue by takahashi-croco** [mmattozzi/cocoa-rest-client#123]
I want the multi-window function introduced by Sierra to be supported.

**Comment by mmattozzi** [comment]
Sorry, I'm not exactly sure what you mean... do you mean the new Split View thing?

**Comment by takahashi-croco** [comment]
Explanation was missing. I'm sorry.

I do not want to use Split View.
I like working with Multiple Windows like TextEdit.app.

Because other rest client is also a Single Window, is it difficult to implement?

**Comment by mmattozzi** [comment]
After watching a session from WWDC2016 (https://developer.apple.com/videos/play/wwdc2016/203/), I think I finally understand what this means. I will definitely give this a try when I drop support for OS X 10.11 and focus on 10.12... probably the release after next.

**Comment by mmattozzi** [comment]
[Version 1.4](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.0) has macOS native tabs and is multi-window!
