### ISSUE TITLE
Run instructions on macOS Sierra

### ISSUE THREAD

**Issue by Bouke** [mmattozzi/cocoa-rest-client#124]
This setting is no longer a thing on macOS Sierra:
> Allow unsigned apps to be installed (System Preferences -> Security & Privacy -> Allow apps downloaded from: "Anywhere"

In order to run unsigned apps, you'd have to richt-click the .app file and choose "Open". After you confirm that you want to run the app, it'll remember that preference and then you can run the app as usual.

**Comment by mmattozzi** [comment]
Thanks! I updated the release notes. I'm sure in 10.13, you'll have to stand on one leg and pat your head.

**Comment by Bouke** [comment]
This also works on all versions of Gatekeeper. I would advise against changing the default to "Anywhere", but on the other hand the setting's already gone on most installations.
