### ISSUE TITLE
Don't automatically send "Accept-Encoding: gzip" on every request

### ISSUE THREAD

**Issue by mjparme** [mmattozzi/cocoa-rest-client#128]
The application appears to automatically send Accept-Encoding: gzip as a header on every request. It would be nice if this wasn't an automatic request header. Instead I will send it if I want to.

**Comment by mmattozzi** [comment]
Fixed in [1.4.1](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.1)

**Comment by mjparme** [comment]
Thanks for this fix!
