### ISSUE TITLE
1.4 premeptive basic auth not working

### ISSUE THREAD

**Issue by lordlele** [mmattozzi/cocoa-rest-client#129]
With 1.3 preemptive basic auth works without any trouble.
Starting from 1.4 the same preemptive basic auth do not send header to server.

**Comment by mmattozzi** [comment]
Ah ha... so it is broken. Looks like I forgot to wire up that checkbox during that big refactor. Thanks!

**Comment by mmattozzi** [comment]
Fixed in [1.4.1](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.1)
