### ISSUE TITLE
Copy Curl Command should include --compressed in curl command if  Accept-Encoding: gzip is included in headers

### ISSUE THREAD

**Issue by mjparme** [mmattozzi/cocoa-rest-client#130]
If the request headers include a compressed encoding in Accept-Encoding (like gzip or deflate) then it would be awesome if the Copy Curl Command menu item produced a curl command that included the "--compressed" command-line option. This lets curl decompress responses that use supported compression algorithms.

From "man curl":

--compressed
              (HTTP) Request a compressed response using one of the algorithms curl supports, and  save
              the  uncompressed  document.   If this option is used and the server sends an unsupported
              encoding, curl will report an error.

**Comment by mmattozzi** [comment]
That sounds like a good idea to me!

**Comment by mmattozzi** [comment]
Released in [Version 1.4.2](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.2)

**Comment by mjparme** [comment]
Nice, thanks!
