### ISSUE TITLE
request: add ability to double click on a blank row to add url params in the new table view

### ISSUE THREAD

**Issue by waterskier2007** [mmattozzi/cocoa-rest-client#131]
similar to the behavior in the headers tab

**Comment by mmattozzi** [comment]
I guess I forgot that when I added the table. It'll be in the next release. Thanks!

**Comment by mmattozzi** [comment]
Fixed in [1.4.3](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.3)
