### ISSUE TITLE
No Windows Menu Item

### ISSUE THREAD

**Issue by ljordan-pea** [mmattozzi/cocoa-rest-client#139]
Thanks for the great application!

CocoaRestClient allows opening multiple windows, which is awesome. But their is no Windows menu item, so windows get lost behind other windows. 

Thanks!

**Comment by mmattozzi** [comment]
Wow, I guess I totally missed that. Hopefully, it shouldn't be too hard to add.

**Comment by mmattozzi** [comment]
Fixed in [Version 1.4.4](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.4)

**Comment by ljordan-pea** [comment]
Thanks!!
