### ISSUE TITLE
how do you import requests?

### ISSUE THREAD

**Issue by bfeldman89** [mmattozzi/cocoa-rest-client#140]
Sorry if this is dumb, but I have no idea how to "import requests." Could that be added to the README.md?

**Comment by mmattozzi** [comment]
`File | Import Requests` is strictly for importing requests saved by this application back into itself... for example, if you want to backup your saved requests somewhere or share your saved requests with somebody else. It is not capable of importing any other file format that somehow specifies an HTTP request. You can create a valid file by using `File | Export Requests...` and selecting the requests you want to export. 

Likewise, if you want to keep multiple computers in sync with the same set of requests, you can try this: https://github.com/mmattozzi/cocoa-rest-client/wiki/How-to-share-saved-requests-between-computers

Generally speaking, if you want to share one request with someone else you can use `Edit | Copy Curl Command` or `CMD-K` to send them a curl one-liner that they can execute on the command line. 

Hope that helps...

**Comment by bfeldman89** [comment]
Thanks!
