### ISSUE TITLE
Selecting method POST is incorrectly submitting as GET

### ISSUE THREAD

**Issue by geigel** [mmattozzi/cocoa-rest-client#144]
I'm using Version 1.4.5 (28) (most recent as of the time of this post) and noticed that when I select the method to be POST it's actually submitting it as GET. I discovered the issue while testing and realizing my $_POST variable in PHP wasn't being populated with my test data. I investigated what method the server was being hit with and it was GET even though POST was chosen in the UI of the app.

I changed the method in the app to other things (e.g. PUT, SEARCH, etc.) and those are correctly submitting okay. Also, the request method on my server was correctly seeing those requests come in with that particular method.

I think there's something that's overriding a method of "POST" in your app to instead execute the call as "GET".

Hope this helps.

**Comment by mmattozzi** [comment]
That's definitely not my experience with the app. As a sanity check, try executing a POST to http://httpbin.org/post with whatever post body you'd like.

**Comment by geigel** [comment]
Thanks for the quick reply. POST-ing to that URL _did_ work. I've tried it on two separate servers and my PHP $_SERVER["REQUEST_METHOD"] is showing "GET" and also my $_POST array isn't being populated (hence me reaching out initially). Give me a minute while I try something else.

**Comment by geigel** [comment]
Man, I am going nuts. On two separate servers my $_POST, $HTTP_RAW_POST_DATA, and file_get_contents("php://input") are completely blank/empty when I'm making a POST call. Yet http://httpbin.org/post is showing the "form" values just fine. I have made POST calls a million times before and never ran into this. Any ideas?

**Comment by geigel** [comment]
Found the issue. The endpoint I was sending data needed to end in "/index.php". I was just ending the endpoint without the filename (e.g. "http://example.com/endpoint/"). Odd because I have sent to just the folder name in the past. Regardless, odd that the http://httpbin.org/post POST request I made to the endpoint without "/index.php" still worked. Will look at deeper and update.

**Comment by geigel** [comment]
This could very well have been a caching issue server-side. Our host has recently implemented new caching mechanisms. Flushing server cache seems to have eliminated the problem. Sorry for the bogus issue submission. Hope this helps someone else if they run into something similar.

**Comment by mmattozzi** [comment]
No problem, sounds good!
