### ISSUE TITLE
Dark Mode Support — macOS Mojave

### ISSUE THREAD

**Issue by barrowclift** [mmattozzi/cocoa-rest-client#155]
A UI update to support macOS Mojave's dark mode would be appreciated. It would help keep CocoaRestClient up-to-date with the Mac's evolving look and feel.

**Comment by mmattozzi** [comment]
Oh yeah, great point... thanks for using the app. I've been developing it on a classic Mac Pro tower (the cheese grater kind) and I just hit the point where I can't really upgrade it to Mojave due to GFX card BS. This might take me a little while as I rethink my Mac situation.

**Comment by barrowclift** [comment]
The classic "cheese grater"! 😄 That's such a shame, Apple's petty spat with Nvidia really is doing more harm than good if it left such a great computer behind as a result.

If that's the case, I'll see what I can do to lend a hand to the dark mode effort once my side project bandwidth opens up, if the help's still needed then.

**Comment by cemck** [comment]
Check #160

**Comment by mmattozzi** [comment]
Finally closed this out in [1.4.6](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.6)
