### ISSUE TITLE
Option for disable Cookies

### ISSUE THREAD

**Issue by adzymaniac** [mmattozzi/cocoa-rest-client#43]
I have problem with the cookies. I can't modifying the request body, will not work if the cookies is set.

**Comment by alexlarocca** [comment]
Great tool but not useful if I can not disable cookie

**Comment by mmattozzi** [comment]
Fixed in Release [1.3.13](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.13) with disable cookies option.
