### ISSUE TITLE
Why is cocoa-rest-client changing the order of properties in the returned JSON?

### ISSUE THREAD

**Issue by asgeo1** [mmattozzi/cocoa-rest-client#46]
My endpoint is returning JSON that looks like this:

    [
       {
         "id" : 2,
         "load_no" : "QWER34568",
         "return_date_scheduled" : "2014-06-27T22:30:00.000000+10:00"
       }
     ]

Yet cocoa-rest-client displays it like so:

    [
       {
         "id" : 2,
         "return_date_scheduled" : "2014-06-27T22:30:00.000000+10:00",
         "load_no" : "QWER34568"
       }
     ]

What's the go with that? It's quite annoying. All the properties are in the wrong order.

I know you shouldn't rely on the order of the properties when working with JSON, but still - for readability I have ordered them in a particular way, and ideally the REST client should just display them in the order they were sent since it's primarily a tool for testing/viewing responses from an endpoint.

**Comment by mmattozzi** [comment]
Fixed in master via ec13e8d814db8c80ad68ec682c31b7b91bc701d1. This will be fixed in the next release.

**Comment by mmattozzi** [comment]
Now in current release.
