### ISSUE TITLE
Switch from GC to ARC

### ISSUE THREAD

**Issue by noamtm** [mmattozzi/cocoa-rest-client#50]
The readme says:

> I will most likely switch to ARC when OS X 10.8 is released. 

10.**9** was released almost a year ago, 10.10 will be released soon. Is there a plan to switch to ARC?
I tried compiling the source on Xcode 5 (on 10.9) and it refuses to support GC. If/when I have time I can switch it myself, but I want to know your plans first.

**Comment by mmattozzi** [comment]
Completed in 8c9e808212d54617b6e3ea21c1ee13ac0babc5a4.
