### ISSUE TITLE
New Cocoa REST Client Icon.... Thoughts ?

### ISSUE THREAD

**Issue by DiegoMax** [mmattozzi/cocoa-rest-client#51]
Hi, on top of all the contributions that im doing to this App, i have also created a new icon, that (in my opinion) represents very well what this application does and looks way more actual than the dated (and low res) one that we currently have.

![App Icon]
(https://www.dropbox.com/s/ankbp9slb92oybv/CRC_icon.jpg?dl=1)

Thougts ??

/cc @mmattozzi

**Comment by Hackmodford** [comment]
Where can I download the icon in the meantime?

**Comment by mmattozzi** [comment]
Icon is here: https://github.com/DiegoMax/cocoa-rest-client/tree/master/CocoaRestClient/Images.xcassets/AppIcon.appiconset 

I'll add it to my project branch soon.

**Comment by DiegoMax** [comment]
Sorry guys I'm crossing the Andes right now ony way to chile. I will be
available tomorrow if u need something

**Comment by mmattozzi** [comment]
Added new icon in commit 7d136c69476eb3bad91e7ef4e4a2d1bc39183bf8!
