### ISSUE TITLE
Garbage collection no longer supported

### ISSUE THREAD

**Issue by DanPen** [mmattozzi/cocoa-rest-client#53]
I forked the repo to create a few minor additions to the app. But when I opened it in Xcode (6.1.1), I get this message:

![screen shot 2014-12-09 at 11 26 06 am](https://cloud.githubusercontent.com/assets/3218721/5362128/346320f6-7f96-11e4-8264-1bd2ab6fff40.png)

Attempting to convert the project gives all sorts of nasty errors and warnings. Certain C structs, such as, `CFStringRef` Xcode doesn't know how to convert. I can't seem to get it to work.

Is anyone working on converting it or is there a workaround available for now?

**Comment by mmattozzi** [comment]
Ok, I switched Fragaria out for [ACEView](https://github.com/faceleg/ACEView) and am now using ARC for this project. I also incorporated [CocoaPods](http://cocoapods.org/). Hopefully I committed all the files I should have.
