### ISSUE TITLE
Crash on launch - reverting back from DiegoMax's fork

### ISSUE THREAD

**Issue by oddysee** [mmattozzi/cocoa-rest-client#55]
A short history: I originally downloaded and built [DeigoMax's fork](https://github.com/DiegoMax/cocoa-rest-client) before discovering that this was the original _and_ that there was a binary install available. I removed DiegoMax's build and installed the build from here.

Now, every launch results in this crash 

    *** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: '*** -    [NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (CRCSavedRequestFolder)'
    abort() called
    terminating with uncaught exception of type NSException

I'm guessing that Cocoa Rest Client stores its settings somewhere and that DeigoMax's build has corrupted these settings. Can I get some directions on what I need to clear/delete to be able to cleanly load Cocoa Rest Client?

**Comment by mmattozzi** [comment]
Delete the contents of ~/Library/Application\ Support/CocoaRestClient/

**Comment by oddysee** [comment]
Thank you, that did it.
