### ISSUE TITLE
Podfile - ACEView Permission denied

### ISSUE THREAD

**Issue by bci** [mmattozzi/cocoa-rest-client#57]
From `pod install`

````
Glinda:cocoa-rest-client kent$ pod install
Analyzing dependencies
# Uncomment this line to define a global platform for your project

CocoaPods 0.36.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Pre-downloading: `ACEView` from `git@github.com:faceleg/ACEView.git`, commit `8edb38c5164ae787c3b271243ca598be9edffdd8`, submodules `true`
[!] /usr/bin/git clone git@github.com:faceleg/ACEView.git /Users/kent/dev/Macintosh/cocoa-rest-client/Pods/ACEView

Cloning into '/Users/kent/dev/Macintosh/cocoa-rest-client/Pods/ACEView'...

Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights

and the repository exists.
````
I've change the Podfile to use just `pod 'ACEView'` - now `pod install` gives: 
````
Analyzing dependencies

CocoaPods 0.36.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Downloading dependencies
Installing ACEView (0.0.4)
Generating Pods project
Integrating client project
````
I now receive the error:

````
/Users/kent/dev/Macintosh/cocoa-rest-client/core/CocoaRestClientAppDelegate.m:480:19: No visible @interface for 'ACEView' declares the selector 'setReadOnly:'
````
I've commented out this line for now.

**Comment by mmattozzi** [comment]
ACEView 0.0.4 has two issues:
* No read only mode (as you observed)
* Cursor placement is messed up

ACEView 0.0.5 hasn't made it into the podspecs catalog yet, so I'm linking directly to the github project. The error you posted here seems to indicate that maybe you don't have your public key set up in github so you can't use ssh to clone a repo. Of course, that makes me wonder how you got the cocoa rest client code down from Github... perhaps you used https for this?

**Comment by bci** [comment]
I'll check the keys - I have moved to a new development system and I may not have captured all the ~/.ssh keys. I'll verify. Thank you.

**Comment by bci** [comment]
Yep, the ssh key in the system had not been used this year. I uploaded a new key and it now pulls the correct version of ACEView. My POST with `application/json` body, and `application/json` response body (nicely formatted!) look good. Thank you.

**Comment by mmattozzi** [comment]
No problem, I should make a mention of this in the readme. Stay tuned... I've got some code I'll be committing in the next day or so that will add theme selection for the ACEView pretty printing.

**Comment by mmattozzi** [comment]
Hey question, since you seem to be building yourself: when you open the project in xcode, does it ask if you want to enable ARC?
