### ISSUE TITLE
Overwrite Request does not seem to work.

### ISSUE THREAD

**Issue by acanewby** [mmattozzi/cocoa-rest-client#62]
Version 1.3.8
OS X 10.9.5

Steps to reproduce:

1. Open previously saved request
2. Make a change (I changed the URL)
3. Select Overwrite Request from menu (or Ctrl Cmd S)
4. Select other request
5. Select original request.  The request is still as it was before the change was made.

**Comment by mmattozzi** [comment]
FIxed in 1.3.9.

**Comment by sweetw0r** [comment]
Shortcut  ⌃⌘S is not working! Version 1.3.9 (14)
