### ISSUE TITLE
JSON pretty-printing does not preserve field ordering

### ISSUE THREAD

**Issue by tekknick** [mmattozzi/cocoa-rest-client#64]
I know it's OCD, but when I design REST resources I care about about field ordering. The current JSON pretty-printer does not preserve field ordering. I didn't realize that this app even had this feature until my co-worker and I were scratching our heads trying to figure out why our application was marshaling JSON with a haphazard field ordering. A nice-to-have would be a View: Pretty Print Response menu item that might make this behavior a little more clear.

**Comment by mmattozzi** [comment]
Do you mean version 1.3.9? I thought I fixed this... do you have an example of a JSON body that gets reordered? Thanks

**Comment by tekknick** [comment]
Yes, version 1.3.9 (14).

$ curl -u nick@tekknick.com http://127.0.0.1:9000/v1/users/30
Enter host password for user 'nick@tekknick.com':
{"userId":30,"emailAddress":"nick@tekknick.com","firstName":"Nick","lastName":"Strecker","gender":"MALE","dateOfBirth":"1978-06-25","heightInCm":196.0,"weightInKg":81.65,"estimatedWorkoutCountPerWeek":6,"estimatedTrainingTimePerWeek":"PT7H","estimated5kTime":"PT28M46S","lastLogin":"2015-05-28T16:32:12.619Z","createdOn":"2015-05-06T02:12:10.971Z","relativeUri":"/v1/users/30"}

—Nick

**Comment by tekknick** [comment]
Yes, version 1.3.9 (14).

![screen shot 2015-05-28 at 9 38 37 am](https://cloud.githubusercontent.com/assets/5225670/7865421/694e88ac-051d-11e5-80f6-2c81c83b0273.png)

![screen shot 2015-05-28 at 9 34 48 am](https://cloud.githubusercontent.com/assets/5225670/7865422/6c16bdd4-051d-11e5-87bb-20c5e9a7df90.png)

**Comment by mmattozzi** [comment]
Finally fixed in [1.3.14](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.14)
