### ISSUE TITLE
Grouped requests are not exported

### ISSUE THREAD

**Issue by sickmartian** [mmattozzi/cocoa-rest-client#65]
Hi, first thanks for your work, it's very useful :+1: 

I'm running 1.3.9 and I have all my requests organized into 'folders', but now the export portion of the program doesn't seem to recognize them.
If I take one out of the folder the export can see it.

![showing single entries on export](https://cloud.githubusercontent.com/assets/492246/7860988/cf106ae2-0523-11e5-9615-b004f83390d9.png)
![no showing anything on export](https://cloud.githubusercontent.com/assets/492246/7860989/cf15962a-0523-11e5-90a6-ba90f8cb17cf.png)

**Comment by narlei** [comment]
This is a problem for me too.

**Comment by acanewby** [comment]
Absolutely love the work!!

+1 on this issue for me too please ...

**Comment by sweetw0r** [comment]
Confirming that I've just faced same issue

**Comment by bkdonline** [comment]
This works with the latest version - issue can be considered closed now.
