### ISSUE TITLE
URL Parameter Interface

### ISSUE THREAD

**Issue by yoiang** [mmattozzi/cocoa-rest-client#67]
Hey @mmattozzi, I just started using Cocoa REST Client and it's great, thanks! 

I have a number of RESTful APIs that use URL parameters, even next to body parameters, and it would be great to be able to see and test combinations of URL parameters how one can with body parameters currently. I'd be happy to create a PR with this support, I just wanted to see if there was a reason you wouldn't want this included.

Thanks again!

**Comment by richardoti** [comment]
The same.
The client looks great and this is the only disadvantage, why I am not using it. POSTMAN has nice interface for params - just below the URL.

**Comment by bkonia** [comment]
Any progress on implementing this? When making a GET request, it should automatically convert the entered params into query string params. It largely defeats the purpose of using this type of app when you have to manually build the query string each time.

**Comment by richardtop** [comment]
@bkonia I switched to Postman, I could recommend it.

**Comment by bkonia** [comment]
Thanks for the suggestion, Richard!

**Comment by mmattozzi** [comment]
URL Parameters table released in [Version 1.4.2](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.2)
