### ISSUE TITLE
JSON Pretty print does not work as expected

### ISSUE THREAD

**Issue by blackat** [mmattozzi/cocoa-rest-client#69]
Hi,
testing a simple REST service I simply get this line
{"content":"Hello World Again","_links":{"self":{"href":"http://localhost:8080/greeting?name=Hello%20World"}}}

not pretty printed, should I have to activate something? I am using the latest version 1.3.9 (14)

Thanks a lot for the attention.
Eugenio

**Comment by cansik** [comment]
+1
Same problem here.

**Comment by mmattozzi** [comment]
The decision of how to format the response is based on the Content-Type header of the response. Is the Content-Type set to `application/json`?

**Comment by cansik** [comment]
That fixed the problem. But not every REST service does return the mime-type. Would be great if there is an option to set the default formatter (or auto detection).

**Comment by nathanpitman** [comment]
+1 same issue here. :)

**Comment by KarimGeiger** [comment]
I'd also like to see this issue being resolved. My service returns application/vnd.api+json as desired by http://jsonapi.org/#mime-types

Making it configurable would be great. As an alternative, you could try parsing JSON if the request Content-Type is application/json.

**Comment by mmattozzi** [comment]
The app now interprets any content-type that ends with `+json` as JSON as well as the standard `application/json` and `text/json`. The same is true of `xml`. I think this should cover most cases.
