### ISSUE TITLE
Add parameters to GET-requests

### ISSUE THREAD

**Issue by richardoti** [mmattozzi/cocoa-rest-client#71]
I would like to add custom parameters to GET request and not to construct it manually in URL. What I mean is that adding parameters to get request should be similar to editing request body. If, for example, we specify these params:
```JSON
q : "StringToSearch"
username : "BadUser"
```
The request should look like:
`http://domain.com/query?q=StringToSearch&username=BadUser`

**Comment by mmattozzi** [comment]
I believe this is the same request as issue #67.

**Comment by richardoti** [comment]
@mmattozzi , oh, yeah!
I was checking the new features and haven't found any of my issues, so I thought, I forgot to mention it.
And, the result is this duplicate. Probably, should be closed.
