### ISSUE TITLE
Import curl command

### ISSUE THREAD

**Issue by greew** [mmattozzi/cocoa-rest-client#73]
Hi.

As written in the About section in the README.md, you love curl but need something more graphical. As do I! :)

Now, my request is that it would be great to have an "Import curl command" function, that can take a curl command, parse it and auto update the view with the corresponding settings. That way, I would be able to use the Google Chrome function "Copy as cURL" and get developing done pretty quickly.

Besides that, thanks for a great piece of software :-)

Best
/Jesper

**Comment by mmattozzi** [comment]
It's a cool idea, I think I (or some other contributor) would have to go deep on all the options of the curl command to make it work.
