### ISSUE TITLE
PUT files is not working

### ISSUE THREAD

**Issue by julian-weinert** [mmattozzi/cocoa-rest-client#74]
For APIs require file PUT requests to contain only the raw image data in the request body.
CocoaRestClient enables be to send files as multipart upload which works just fine.
Also the "Raw Input" checkbox helps a lot when dealing with text-based endpoint.

However, when, for example, trying to `PUT` a file on an AWS S3 bucket, this is just not possible.

So I'd like to have a "Raw _File_ Input" feature.

Stay being awesome – Many thanks for this tool!

**Comment by mmattozzi** [comment]
This is a good suggestion, may not be that hard to add. Thanks!

**Comment by mmattozzi** [comment]
Whoa. I really let this issue sit around for a while. This is already possible although maybe not obvious. 
* Check the "Raw Input" box on the body tab
* Add the file to the Files tab
* Set the Content-Type to whatever it needs to be (something other than multipart) on the Headers tab

This should post only the bytes of the file to the URL provided for POSTs or PUTs.
