### ISSUE TITLE
Tabs (Feature Request)

### ISSUE THREAD

**Issue by nathanpitman** [mmattozzi/cocoa-rest-client#76]
It would be super useful if you could initiate tabs within this app, often you might want to test a number of API calls without having to clear previous states. :)

**Comment by narlei** [comment]
+1

**Comment by mmattozzi** [comment]
Yeah, I agree... it's a fair bit of UI work so I've been putting off stuff like that for a while. I was lost in xcode autolayout hell just trying to make the spacer between the request and the response adjustable... :(

**Comment by sweetw0r** [comment]
Yeah, it is so necessary! It is down side of this amazing app :(

**Comment by Fudge0952** [comment]
+1 Definitely would make for an amazing app (well already is an amazing app).

**Comment by DiegoMax** [comment]
I might implement this if there is enough demand :)

**Comment by sweetw0r** [comment]
Check new Postman for Mac out! No more Chrome required. Hooray Safari users 🤓

**Comment by mmattozzi** [comment]
[Version 1.4](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.0) has macOS native tabs and is multi-window!
