### ISSUE TITLE
Update instead of insert on save

### ISSUE THREAD

**Issue by Bouke** [mmattozzi/cocoa-rest-client#78]
After a request has been saved, saving a second time should simply overwrite the previous version. Currently a new request is appended to the Request Drawer.

**Comment by inglar** [comment]
Bouke, you can use "control - command - s" to overwrite request

**Comment by Bouke** [comment]
I would expect "Save Request" to adhere to the established document model; so when a "document" is selected in the picker, the "Save Request" would operate on that "document", thus overwriting the previous version.

**Comment by brki** [comment]
I agree with @Bouke that it would be more intuitive if these were the two menu entries to save:
* "Save": save, overwriting a previous version, or creating a new one if none already exists
* "Save as new request" (only available if a saved version already exists): saves a new copy with a new name to the drawer.

**Comment by mmattozzi** [comment]
Fixed in Release 1.3.16.
