### ISSUE TITLE
Adjustable size of Request/Response window (Feature Request)

### ISSUE THREAD

**Issue by sweetw0r** [mmattozzi/cocoa-rest-client#80]
Sometimes Request/Response window contains thousands lines and it becomes very annoying to scroll these lines. Would be much better if user can just drug between Request and Response windows to adjust the size of them. 
![screen shot 2015-11-03 at 11 50 47 am](https://cloud.githubusercontent.com/assets/12688470/10919801/9a5f077e-8221-11e5-8137-1a2aeb9a2a93.png)

**Comment by DiegoMax** [comment]
This, and many other UI things are on a PR that i just submitted.
https://github.com/mmattozzi/cocoa-rest-client/pull/91

**Comment by mmattozzi** [comment]
Fixed in [1.3.11](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.11)
