### ISSUE TITLE
Remember "Content-Type" setting

### ISSUE THREAD

**Issue by gdubicki** [mmattozzi/cocoa-rest-client#81]
Let me start with a big thank you for this nice app! :)

I use it almost exclusively to access REST APIs and with each start of the app I have to switch "Raw input" flag to "on" and "Content-Type" to "application/json". This is annoying. Could you please make these setting being remembered between application starts?

**Comment by DiegoMax** [comment]
This, and many other things are on a pull request that i just sent, hopefully it will get merged :dancer: 
https://github.com/mmattozzi/cocoa-rest-client/pull/90

**Comment by gdubicki** [comment]
Closing as #90 has been merged, @mmattozzi ?

**Comment by gdubicki** [comment]
Sorry, premature close - "Raw input" is now saved between launches, but "Content-Type" is still not.

**Comment by mmattozzi** [comment]
Fixed in [1.4.1](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.4.1)
