### ISSUE TITLE
DELETE request

### ISSUE THREAD

**Issue by pjebs** [mmattozzi/cocoa-rest-client#85]
The body data does not seem to get sent when the request method is "DELETE"

**Comment by pjebs** [comment]
https://github.com/mmattozzi/cocoa-rest-client/issues/68

DELETE requests can have a body now: 

Please refer to new specificiations:

http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-19#page-23

**Comment by mmattozzi** [comment]
Fixed in Release [1.3.13](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.13).
