### ISSUE TITLE
JSON response gets reinterpreted with float precision issue

### ISSUE THREAD

**Issue by lost-carrier** [mmattozzi/cocoa-rest-client#86]
I'm using the latest 1.3.10 (15) of CocoaRestClient running.

Similar to that issue reported in https://github.com/mmattozzi/cocoa-rest-client/issues/64, I additionally have precision issues with floats and doubles in JSON format.

<img width="915" alt="bildschirmfoto 2016-01-13 um 09 49 28" src="https://cloud.githubusercontent.com/assets/3090579/12289320/1c767756-b9db-11e5-8fc5-cd8ee2621c59.png">

**Comment by mmattozzi** [comment]
Finally fixed in [1.3.14](https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.14).
