### ISSUE TITLE
Tab does not move to password field in Auth section

### ISSUE THREAD

**Issue by jlindenbaum** [mmattozzi/cocoa-rest-client#96]
Version: Version 1.3.11 (16)

Steps to reproduce
- Go into `Auth` section
- Type username for basic auth
- Hit tab key
- Username highlights

Expected
- Type user name for basic auth
- Hit tab key
- Cursor moves to basic auth password field

**Comment by mmattozzi** [comment]
Fixed in https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.12
