### ISSUE TITLE
HTTP response status no longer shown in "Headers"

### ISSUE THREAD

**Issue by gitfan13** [mmattozzi/cocoa-rest-client#97]
Dear Mike,

there are three "tabs" in the lower (RESPONSE) half of the main window: Body, Headers, Sent Headers.

In the previous version I loved the feature that after hitting "Submit" the "Header" title changed to "Headers (403)" or whatever the response code from the server was.

In the newest version the response code is no longer shown, so I sometimes think that nothing happened. For example if the "Body" tab is currently active and I hit submit. If the server returns a 403 and no body, then nothing changes, and I have to actively think of switching to the "Headers" tab to see the answer.

It would be great to get the old behavior back.

Thanks a million!

**Comment by mmattozzi** [comment]
I agree, that is a missing piece... I just noticed that last night and started working on restoring it.

**Comment by mmattozzi** [comment]
Fixed in https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.12

**Comment by gitfan13** [comment]
Perfect, tanks! :-)
