### ISSUE TITLE
Import requests seems to be broken in latest version

### ISSUE THREAD

**Issue by shylacs** [mmattozzi/cocoa-rest-client#98]
Nothing happens when I try to import requests. This was working fine till I upgraded to the latest version (1.3.11(16)).

**Comment by mmattozzi** [comment]
Whoops, that does seem to be the case... will work on getting this fixed.

**Comment by mmattozzi** [comment]
Fixed in https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.12
