### ISSUE TITLE
Open response in browser does not work

### ISSUE THREAD

**Issue by petr-inmite** [mmattozzi/cocoa-rest-client#99]
Version 1.3.11 (16)

When I click "File > View Response in Browser", nothing happens. It used to be the case in previous versions as well, but in "File > View Response in Default App" opened browser - now it opens a Text Edit app.

It would be nice to have settings for the default app (I would chose Atom) and browser (Chrome). ;-)

**Comment by mmattozzi** [comment]
Hmm... what's the Content-Type of the response you're looking at?

**Comment by mmattozzi** [comment]
Why this stopped working is a bit of a mystery to me... @DiegoMax any thoughts? I need to dig in a little more. Or maybe I'm missing something obvious.

**Comment by petr-inmite** [comment]
Thank you for a quick response!

The response HTTP headers are:

```http
HTTP 500 Internal Server Error

Connection: close
X-Powered-By: Nette Framework
Pragma: no-cache
Vary: X-Requested-With
Content-Type: text/html; charset=UTF-8
Set-Cookie: PHPSESSID=j0in76hiiar1sbi1ulof6nf646; expires=Sat, 30-Apr-2016 15:58:11 GMT; Max-Age=1209600; path=/; httponly, nette-browser=hywdaehnl5; path=/; httponly
Host: localhost:8010
X-Frame-Options: SAMEORIGIN
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
```

**Comment by DiegoMax** [comment]
I will take a look at this but you will have to give me a few days, im in the middle of a long plane trip going back home in a few hours :p

**Comment by DiegoMax** [comment]
If there are any other bugs that appeared after all my changes, please mention me on the issues too, so that i can fix those too. Cheers!

**Comment by DiegoMax** [comment]
Question tho, what is "open response in browser" supposed to do ?

**Comment by DiegoMax** [comment]
I think my question is not clear enough, what i mean is, for cases for the status 500 mentioned here, how are you supposed to open an already sent request on a browser in a way that is not sending the request again ? am i missing something here ?

**Comment by petr-inmite** [comment]
Launch the default system browser and pass it a path to the file with the content of response...

My use case is following:

I am building a RESTful API in PHP and I use Tracy for debugging (https://tracy.nette.org/en/). Anytime an exception occurs, I can see a nice HTML code with a stack trace, but I need to be able to open it in the browser...

**Comment by DiegoMax** [comment]
Ok, so basically the process would be.
1) Save response headers and body into a text file
2) Open it in a browser

Right ?

**Comment by DiegoMax** [comment]
As far as i can remember i wrote code to do exactly that, but i think the problem might be regarding the 500 status code.... i need to re-check my code.

**Comment by petr-inmite** [comment]
Body should be enough - the headers are sort of "technical" and can be viewed in the REST client well enough. Storing them in the same file would probably just break the output. The main use-case for me is HTML code rendering and maybe, sometimes I could use browser to render JSON as well (to get larger screen estate)...

**Comment by DiegoMax** [comment]
Got it.

**Comment by DiegoMax** [comment]
Question is, what would happen with things that the browser cant understand.

**Comment by DiegoMax** [comment]
Like, for example, safari on mac would just download a file if the content-type is application/json.... and im sure there are many other edge cases like that.

**Comment by DiegoMax** [comment]
Sorry for all the ranting, im just trying to think on a solution that works for all possible cases :)

**Comment by petr-inmite** [comment]
That's why settings could be nice. ;-) I could use Safari as the default browser and Chrome for development.

But let's not overthink it now. The question isn't "what browser cannot handle" but that "there is a use-case for the things that browser can handle". :)

I will not call "Open in web browser" action to open let's say a proprietary encrypted binary content (and even if I will click the action, I will be happy for the weird browser reaction, like download of a binary file), but mostly I will use it for HTML / text-based format response.

**Comment by DiegoMax** [comment]
i can confirm that my code is working on the current released version, as a matter of fact, i wrote a lot of code to deal with that as part of my refactors.
I have just tested a lot of strange statues using this: http://httpstat.us and they all seem to work.
I can not make it fail on my side, this must be something specific regarding the body of your specific request... any chance you can provide a testing endpoint that is failing for you ?
What is your system default browser ?
```
- (NSString *) saveResponseToTempFile {
    NSString *tempDir = NSTemporaryDirectory();
    
    static int sequenceNumber = 0;
    NSString *path;
    do {
        sequenceNumber++;
        path = [NSString stringWithFormat:@"%d-%d-%d.txt", [[NSProcessInfo processInfo] processIdentifier],
                (int)[NSDate timeIntervalSinceReferenceDate], sequenceNumber];
        path = [tempDir stringByAppendingPathComponent:path];
    } while ([[NSFileManager defaultManager] fileExistsAtPath:path]);
    
    NSLog(@"Saving to %@", path);
    NSError *error;
    BOOL savedOK = [[self getResponseText] writeToFile:path atomically:YES encoding:NSUTF8StringEncoding error:&error];
    
    if (! savedOK) {
        NSLog(@"Error writing file at %@\n%@", path, [error localizedFailureReason]);
        NSAlert *alert = [[NSAlert alloc] init];
        [alert addButtonWithTitle:@"OK"];
        [alert setMessageText:@"Unable to save response as temp file"];
        [alert setInformativeText:[error localizedFailureReason]];
        [alert setAlertStyle:NSWarningAlertStyle];
        [alert runModal];
        return nil;
    } else {
        return path;
    }
}
- (IBAction) viewResponseInBrowser:(id)sender {
    NSString *path = [self saveResponseToTempFile];
    if (path) {
        NSURL *defaultBrowserURL =
        [[NSWorkspace sharedWorkspace]URLForApplicationToOpenURL:[NSURL URLWithString:@"http://google.com"]];
        [[NSWorkspace sharedWorkspace]openFile:path.stringByStandardizingPath
                               withApplication:defaultBrowserURL.absoluteString.lastPathComponent];
    }
}
```

**Comment by petr-inmite** [comment]
Here is my system info:

- Mac OS X El Capitan - 10.11.4 (15E65)
- Google Chrome - Version 49.0.2623.110 (64-bit)

Calling:

```bash
$ open http://google.com/
```

Opens Chrome for me correctly.

Still, it does not work for me with any request in 1.3.11 version. :( Even a "vanilla GET response" with http://google.com/ as request URL does not open for me.

**Comment by petr-inmite** [comment]
OK, cloned the repo and I see the source of the error:

```
(lldb) print defaultBrowserURL.absoluteString.lastPathComponent
(NSPathStore2 *) $1 = 0x0000600000462f80 @"Google%20Chrome.app"
```

The issue is that Chrome is called "Google Chrome.app" which is percent encoded.

Change the last line in IBAction to:

[[NSWorkspace sharedWorkspace]openFile:path.stringByStandardizingPath

```objc                               defaultBrowserURL.absoluteString.lastPathComponent**.stringByRemovingPercentEncoding**
```

... and you are good to go! :)

**Comment by DiegoMax** [comment]
yeah i was about to do a pull request with that same fix written in a different way, but yes, thats the problem. It started to happen to me as soon as i switched from safari.app to google chrome.app ;) thanks for the report!

**Comment by petr-inmite** [comment]
No problem! :) There is one more thing related to this one.

I would consider refactoring the "saveResponseToTempFile" to accept a suffix parameter - opening "*.txt" file in browser will open it as ... well... text file. :) The suffix could respect the return content type.

**Comment by mmattozzi** [comment]
Great catch on this one..! Thanks for figuring it out... Good suggestion about setting the suffix appropriately. To @petr-inmite's early point about choosing the application, I wonder if there's an easy way to emulate the Open With menu in Finder.

**Comment by mmattozzi** [comment]
Fixed in https://github.com/mmattozzi/cocoa-rest-client/releases/tag/1.3.12
